<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <OutputType>Exe</OutputType>
    <OutputType Condition="$([MSBuild]::IsOSPlatform('windows'))">WinExe</OutputType>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sinos.Common\Sinos.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Watch Include="**\*.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\PlotEditor.axaml.cs">
      <DependentUpon>PlotEditor.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ProgressWindow.axaml.cs">
      <DependentUpon>ProgressWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
