<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Quark</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.21.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="ProcessX" Version="1.5.5" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quark.DependencyInjection\Quark.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
